$ROOT_DIR/source/rtl/decimator.v
$ROOT_DIR/source/rtl/clk_divider.v
$ROOT_DIR/source/rtl/clk_rst_gen.v
$ROOT_DIR/source/rtl/signal_sync.v
$ROOT_DIR/source/rtl/loop_filter.v
$ROOT_DIR/source/rtl/regfile.v
$ROOT_DIR/source/rtl/spi_if.v
$ROOT_DIR/source/rtl/reset_sync.v
$ROOT_DIR/source/rtl/loop_divider.v
$ROOT_DIR/source/rtl/digital_loop_filter.v
$ROOT_DIR/source/tb/adhoc/digital_loop_filter/digital_loop_filter_tb.v
