// -------------------------------------------------------------
// 
// File Name: hdlsrc/cic_test_mdl/loop_filter.v
// Created: 2015-06-06 00:59:10
// 
// Generated by MATLAB 8.1 and HDL Coder 3.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.6e-09
// Target subsystem base rate: 2.56e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ceout         2.56e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// filter_out                    ceout         2.56e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: loop_filter
// Source Path: cic_test_mdl/loop_filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------



module loop_filter
          (/*AUTOARG*/
   // Outputs
   ceout, filter_out,
   // Inputs
   clk, rstn, enable, filter_in, a2, a3, b1, b2
   );


  input   clk;
  input   rstn;
  input   enable;
  input   signed [15:0] filter_in;  // sfix16_En15
  output  ceout;
  output  signed [15:0] filter_out;  // sfix16_En15
  input signed [15:0] a2;
  input signed [15:0] a3;
  input signed [15:0] b1;
  input signed [15:0] b2;

  wire enb_1_16_0;
  wire signed [31:0] b_1_out1;  // sfix32_En28
  wire signed [31:0] b_2_out1;  // sfix32_En28
  wire signed [15:0] CastCAS_out1;  // sfix16_En15
  wire signed [31:0] a_2_out1;  // sfix32_En29
  wire signed [31:0] a_3_out1;  // sfix32_En29
  wire signed [15:0] CastStates3_out1;  // sfix16_En10
  reg signed [15:0] BodyDelay3_out1;  // sfix16_En10
  wire signed [34:0] BodyLSum2_sub_cast;  // sfix35_En29
  wire signed [35:0] BodyLSum2_sub_cast_1;  // sfix36_En29
  wire signed [34:0] BodyLSum2_sub_cast_2;  // sfix35_En29
  wire signed [35:0] BodyLSum2_sub_cast_3;  // sfix36_En29
  wire signed [35:0] BodyLSum2_sub_temp;  // sfix36_En29
  wire signed [34:0] BodyLSum2_out1;  // sfix35_En29
  wire signed [35:0] BodyRSum2_sub_cast;  // sfix36_En29
  wire signed [34:0] BodyRSum2_sub_cast_1;  // sfix35_En29
  wire signed [35:0] BodyRSum2_sub_cast_2;  // sfix36_En29
  wire signed [35:0] BodyRSum2_sub_temp;  // sfix36_En29
  wire signed [34:0] BodyRSum2_out1;  // sfix35_En29
  wire signed [15:0] CastStates2_out1;  // sfix16_En10
  reg signed [15:0] BodyDelay2_out1;  // sfix16_En10
  wire signed [34:0] HeadSum1_add_cast;  // sfix35_En29
  wire signed [35:0] HeadSum1_add_cast_1;  // sfix36_En29
  wire signed [34:0] HeadSum1_add_cast_2;  // sfix35_En29
  wire signed [35:0] HeadSum1_add_cast_3;  // sfix36_En29
  wire signed [35:0] HeadSum1_add_temp;  // sfix36_En29
  wire signed [34:0] HeadSum1_out1;  // sfix35_En29


  assign b_1_out1 = b1 * filter_in;



  assign b_2_out1 = b2 * filter_in;



  assign enb_1_16_0 = enable;

  assign a_2_out1 = a2 * CastCAS_out1;



  assign a_3_out1 = a3 * CastCAS_out1;



  assign CastStates3_out1 = {{3{a_3_out1[31]}}, a_3_out1[31:19]};



  always @(posedge clk or negedge rstn)
    begin : BodyDelay3_process
      if (rstn == 1'b0) begin
        BodyDelay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_16_0) begin
          BodyDelay3_out1 <= CastStates3_out1;
        end
      end
    end



  assign BodyLSum2_sub_cast = {{2{b_2_out1[31]}}, {b_2_out1, 1'b0}};
  assign BodyLSum2_sub_cast_1 = BodyLSum2_sub_cast;
  assign BodyLSum2_sub_cast_2 = {BodyDelay3_out1, 19'b0000000000000000000};
  assign BodyLSum2_sub_cast_3 = BodyLSum2_sub_cast_2;
  assign BodyLSum2_sub_temp = BodyLSum2_sub_cast_1 - BodyLSum2_sub_cast_3;
  assign BodyLSum2_out1 = ((BodyLSum2_sub_temp[35] == 1'b0) && (BodyLSum2_sub_temp[34] != 1'b0) ? 35'sh3FFFFFFFF :
              ((BodyLSum2_sub_temp[35] == 1'b1) && (BodyLSum2_sub_temp[34] != 1'b1) ? 35'sh400000000 :
              $signed(BodyLSum2_sub_temp[34:0])));



  assign BodyRSum2_sub_cast = BodyLSum2_out1;
  assign BodyRSum2_sub_cast_1 = a_2_out1;
  assign BodyRSum2_sub_cast_2 = BodyRSum2_sub_cast_1;
  assign BodyRSum2_sub_temp = BodyRSum2_sub_cast - BodyRSum2_sub_cast_2;
  assign BodyRSum2_out1 = ((BodyRSum2_sub_temp[35] == 1'b0) && (BodyRSum2_sub_temp[34] != 1'b0) ? 35'sh3FFFFFFFF :
              ((BodyRSum2_sub_temp[35] == 1'b1) && (BodyRSum2_sub_temp[34] != 1'b1) ? 35'sh400000000 :
              $signed(BodyRSum2_sub_temp[34:0])));



  assign CastStates2_out1 = ((BodyRSum2_out1[34] == 1'b0) && (BodyRSum2_out1[33:19] == 15'b111111111111111) ? 16'sb0111111111111111 :
              $signed(BodyRSum2_out1[34:19]));



  always @(posedge clk or negedge rstn)
    begin : BodyDelay2_process
      if (rstn == 1'b0) begin
        BodyDelay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_16_0) begin
          BodyDelay2_out1 <= CastStates2_out1;
        end
      end
    end



  assign HeadSum1_add_cast = {{2{b_1_out1[31]}}, {b_1_out1, 1'b0}};
  assign HeadSum1_add_cast_1 = HeadSum1_add_cast;
  assign HeadSum1_add_cast_2 = {BodyDelay2_out1, 19'b0000000000000000000};
  assign HeadSum1_add_cast_3 = HeadSum1_add_cast_2;
  assign HeadSum1_add_temp = HeadSum1_add_cast_1 + HeadSum1_add_cast_3;
  assign HeadSum1_out1 = ((HeadSum1_add_temp[35] == 1'b0) && (HeadSum1_add_temp[34] != 1'b0) ? 35'sh3FFFFFFFF :
              ((HeadSum1_add_temp[35] == 1'b1) && (HeadSum1_add_temp[34] != 1'b1) ? 35'sh400000000 :
              $signed(HeadSum1_add_temp[34:0])));



  assign CastCAS_out1 = ((HeadSum1_out1[34] == 1'b0) && (HeadSum1_out1[33:29] != 5'b00000) ? 16'sb0111111111111111 :
              ((HeadSum1_out1[34] == 1'b1) && (HeadSum1_out1[33:29] != 5'b11111) ? 16'sb1000000000000000 :
              $signed(HeadSum1_out1[29:14])));



  assign filter_out = CastCAS_out1;

  assign ceout = enable;

endmodule  // loop_filter

