// -------------------------------------------------------------
// 
// File Name: /home/amr/work/comm_prj/matlab/hdlsrc/digital_loop_filter/loop_filter.v
// Created: 2015-09-18 22:21:10
// 
// Generated by MATLAB 8.1 and HDL Coder 3.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1.6e-09
// Target subsystem base rate: 2.56e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ceout         2.56e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// filter_out                    ceout         2.56e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: loop_filter
// Source Path: digital_loop_filter/loop_filter
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module loop_filter
          (
           clk,
           rstn,
           enable,
           filter_in,
           ceout,
           filter_out,
           a2,a3,b1,b2
          );


  input   clk;
  input   rstn;
  input   enable;
  input   signed [15:0] filter_in;  // int16
  output  ceout;
  output  signed [15:0] filter_out;  // int16
  input signed [17:0] a2,a3,b1,b2;


  wire enb_1_16_0;
  wire signed [33:0] b_1_out1;  // sfix34_En15
  wire signed [33:0] b_2_out1;  // sfix34_En15
  wire signed [15:0] CastCAS_out1;  // int16
  wire signed [33:0] a_2_out1;  // sfix34_En16
  wire signed [33:0] a_3_out1;  // sfix34_En16
  wire signed [15:0] CastStates3_out1;  // sfix16_E5
  reg signed [15:0] BodyDelay3_out1;  // sfix16_E5
  wire signed [36:0] BodyLSum2_sub_cast;  // sfix37_En16
  wire signed [37:0] BodyLSum2_sub_cast_1;  // sfix38_En16
  wire signed [36:0] BodyLSum2_sub_cast_2;  // sfix37_En16
  wire signed [37:0] BodyLSum2_sub_cast_3;  // sfix38_En16
  wire signed [37:0] BodyLSum2_sub_temp;  // sfix38_En16
  wire signed [36:0] BodyLSum2_out1;  // sfix37_En16
  wire signed [37:0] BodyRSum2_sub_cast;  // sfix38_En16
  wire signed [36:0] BodyRSum2_sub_cast_1;  // sfix37_En16
  wire signed [37:0] BodyRSum2_sub_cast_2;  // sfix38_En16
  wire signed [37:0] BodyRSum2_sub_temp;  // sfix38_En16
  wire signed [36:0] BodyRSum2_out1;  // sfix37_En16
  wire signed [15:0] CastStates2_out1;  // sfix16_E5
  reg signed [15:0] BodyDelay2_out1;  // sfix16_E5
  wire signed [36:0] HeadSum1_add_cast;  // sfix37_En16
  wire signed [37:0] HeadSum1_add_cast_1;  // sfix38_En16
  wire signed [36:0] HeadSum1_add_cast_2;  // sfix37_En16
  wire signed [37:0] HeadSum1_add_cast_3;  // sfix38_En16
  wire signed [37:0] HeadSum1_add_temp;  // sfix38_En16
  wire signed [36:0] HeadSum1_out1;  // sfix37_En16


  assign b_1_out1 = b1 * filter_in;



  assign b_2_out1 = b2 * filter_in;



  assign enb_1_16_0 = enable;

  assign a_2_out1 = a2 * CastCAS_out1;



  assign a_3_out1 = a3 * CastCAS_out1;



  assign CastStates3_out1 = {{3{a_3_out1[33]}}, a_3_out1[33:21]};



  always @(posedge clk or negedge rstn)
    begin : BodyDelay3_process
      if (rstn == 1'b0) begin
        BodyDelay3_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_16_0) begin
          BodyDelay3_out1 <= CastStates3_out1;
        end
      end
    end



  assign BodyLSum2_sub_cast = {{2{b_2_out1[33]}}, {b_2_out1, 1'b0}};
  assign BodyLSum2_sub_cast_1 = BodyLSum2_sub_cast;
  assign BodyLSum2_sub_cast_2 = {BodyDelay3_out1, 21'b000000000000000000000};
  assign BodyLSum2_sub_cast_3 = BodyLSum2_sub_cast_2;
  assign BodyLSum2_sub_temp = BodyLSum2_sub_cast_1 - BodyLSum2_sub_cast_3;
  assign BodyLSum2_out1 = ((BodyLSum2_sub_temp[37] == 1'b0) && (BodyLSum2_sub_temp[36] != 1'b0) ? 37'sh0FFFFFFFFF :
              ((BodyLSum2_sub_temp[37] == 1'b1) && (BodyLSum2_sub_temp[36] != 1'b1) ? 37'sh1000000000 :
              $signed(BodyLSum2_sub_temp[36:0])));



  assign BodyRSum2_sub_cast = BodyLSum2_out1;
  assign BodyRSum2_sub_cast_1 = a_2_out1;
  assign BodyRSum2_sub_cast_2 = BodyRSum2_sub_cast_1;
  assign BodyRSum2_sub_temp = BodyRSum2_sub_cast - BodyRSum2_sub_cast_2;
  assign BodyRSum2_out1 = ((BodyRSum2_sub_temp[37] == 1'b0) && (BodyRSum2_sub_temp[36] != 1'b0) ? 37'sh0FFFFFFFFF :
              ((BodyRSum2_sub_temp[37] == 1'b1) && (BodyRSum2_sub_temp[36] != 1'b1) ? 37'sh1000000000 :
              $signed(BodyRSum2_sub_temp[36:0])));



  assign CastStates2_out1 = ((BodyRSum2_out1[36] == 1'b0) && (BodyRSum2_out1[35:21] == 15'b111111111111111) ? 16'sb0111111111111111 :
              $signed(BodyRSum2_out1[36:21]));



  always @(posedge clk or negedge rstn)
    begin : BodyDelay2_process
      if (rstn == 1'b0) begin
        BodyDelay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb_1_16_0) begin
          BodyDelay2_out1 <= CastStates2_out1;
        end
      end
    end



  assign HeadSum1_add_cast = {{2{b_1_out1[33]}}, {b_1_out1, 1'b0}};
  assign HeadSum1_add_cast_1 = HeadSum1_add_cast;
  assign HeadSum1_add_cast_2 = {BodyDelay2_out1, 21'b000000000000000000000};
  assign HeadSum1_add_cast_3 = HeadSum1_add_cast_2;
  assign HeadSum1_add_temp = HeadSum1_add_cast_1 + HeadSum1_add_cast_3;
  assign HeadSum1_out1 = ((HeadSum1_add_temp[37] == 1'b0) && (HeadSum1_add_temp[36] != 1'b0) ? 37'sh0FFFFFFFFF :
              ((HeadSum1_add_temp[37] == 1'b1) && (HeadSum1_add_temp[36] != 1'b1) ? 37'sh1000000000 :
              $signed(HeadSum1_add_temp[36:0])));



  assign CastCAS_out1 = ((HeadSum1_out1[36] == 1'b0) && (HeadSum1_out1[35:31] != 5'b00000) ? 16'sb0111111111111111 :
              ((HeadSum1_out1[36] == 1'b1) && (HeadSum1_out1[35:31] != 5'b11111) ? 16'sb1000000000000000 :
              $signed(HeadSum1_out1[31:16])));



  assign filter_out = CastCAS_out1;

  assign ceout = enable;

endmodule  // loop_filter

